### ISSUE TITLE
SAR crashes Portal 1 (v. 5135) upon attempting to load

### ISSUE THREAD

**Issue by Cant-Even** [NeKzor/SourceAutoRecord#16]
Using the Source Unpack version of Portal, on Windows 10, and with no other plugins loaded, typing "plugin_load sar" into the console immediately crashes the game, and I can't use any of the epic features :(

**Comment by NeKzor** [comment]
Source Unpack is **currently not supported.** I know it probably doesn't make sense since nobody really runs on SteamPipe. The reason why I chose the latest engine is because I want to provide everyone (except Mac users) the same tool. It might take a while to add support for older engines but I don't have any plans for that at the moment. Maybe someone else with enough motivation and knowledge in reversing will do it .

I guess I should also mention that somewhere.

**Comment by NeKzor** [comment]
Good news: #23 

(don't know where the motivation came from but the tiny engine differences gave me some headache)
